### ISSUE TITLE
程序报错

### ISSUE THREAD

**Issue by 15315250150** [stark81/my_yesplaymusic#1]
# 尽量每个 issue 只提一个 bug 或新功能
A JavaScript error occurred in the main process
你好，打开软件提示这个错误，怎么解决？

**Comment by stark81** [comment]
你的来信已经收到，我将会尽快给你回复。

**Comment by stark81** [comment]
给个截图呗兄弟

**Comment by stark81** [comment]
没有回复就关闭了哟

**Comment by YvGuo-YY** [comment]
<img width="520" alt="image" src="https://github.com/stark81/my_yesplaymusic/assets/54350593/ce524fa4-2893-4e0a-9ab2-fa9f70dd9241">

**Comment by YvGuo-YY** [comment]
就报这个错误
我刚安装的

**Comment by YvGuo-YY** [comment]
m1 pro
0.4.7原版的，音源，总是谁谁谁的录歌我吐了

**Comment by stark81** [comment]
> 环境：m1 pro
> 发版我可以帮忙测试，我不知道这里留言你会不会收到，没回复的话，等几天我就新建issue

是直接下载的安装包吗？可以重新下载安装试一试。m1 pro可以用那个arm或者universal？

**Comment by stark81** [comment]
在GitHub上没看到你的issues。音源问题，可以在设置的unblocknetnease music里设置备选音源，可以试试优先qq源之类的。发自我的 iPhone在 2023年8月30日，16:37，shenghui_niu ***@***.***> 写道：﻿
m1 pro
0.4.7原版的，音源，总是谁谁谁的录歌我吐了

**Comment by YvGuo-YY** [comment]
> > 环境：m1 pro
> > 发版我可以帮忙测试，我不知道这里留言你会不会收到，没回复的话，等几天我就新建issue
> 
> 你看你之前的回复是说播放出来的歌曲不是原版吗？那应该是没有设置UnblockNeteaseMusic，可以按照“设置-UnblockNeteaseMusic”里的“可以点此到 UNM 的说明页面查询”说明来进行设置备选音源，可以设置为优先使用qq源，我设置好之后听Jay的歌基本没有什么问题。

不不不，这些都打开了，就是错乱，还是比较正常的，主要是还想找一个带评论和歌词的，你上面说的两种方法我都试了，没用

**Comment by stark81** [comment]
> > > 环境：m1 pro
> > > 发版我可以帮忙测试，我不知道这里留言你会不会收到，没回复的话，等几天我就新建issue
> > 
> > 
> > 你看你之前的回复是说播放出来的歌曲不是原版吗？那应该是没有设置UnblockNeteaseMusic，可以按照“设置-UnblockNeteaseMusic”里的“可以点此到 UNM 的说明页面查询”说明来进行设置备选音源，可以设置为优先使用qq源，我设置好之后听Jay的歌基本没有什么问题。
> 
> 不不不，这些都打开了，就是错乱，还是比较正常的，主要是还想找一个带评论和歌词的，你上面说的两种方法我都试了，没用

**Comment by stark81** [comment]
> > > 环境：m1 pro
> > > 发版我可以帮忙测试，我不知道这里留言你会不会收到，没回复的话，等几天我就新建issue
> > 
> > 
> > 你看你之前的回复是说播放出来的歌曲不是原版吗？那应该是没有设置UnblockNeteaseMusic，可以按照“设置-UnblockNeteaseMusic”里的“可以点此到 UNM 的说明页面查询”说明来进行设置备选音源，可以设置为优先使用qq源，我设置好之后听Jay的歌基本没有什么问题。
> 
> 不不不，这些都打开了，就是错乱，还是比较正常的，主要是还想找一个带评论和歌词的，你上面说的两种方法我都试了，没用

还是有点没看懂你的意思。是说你已经设置好了备用音源，但是它匹配出来的歌曲都不是原版，没有歌词和评论吗？你可以把有问题的歌曲发一下，我这边也测试看看是否正常。

**Comment by YvGuo-YY** [comment]
> > > > 环境：m1 pro
> > > > 发版我可以帮忙测试，我不知道这里留言你会不会收到，没回复的话，等几天我就新建issue
> > > 
> > > 
> > > 你看你之前的回复是说播放出来的歌曲不是原版吗？那应该是没有设置UnblockNeteaseMusic，可以按照“设置-UnblockNeteaseMusic”里的“可以点此到 UNM 的说明页面查询”说明来进行设置备选音源，可以设置为优先使用qq源，我设置好之后听Jay的歌基本没有什么问题。
> > 
> > 
> > 不不不，这些都打开了，就是错乱，还是比较正常的，主要是还想找一个带评论和歌词的，你上面说的两种方法我都试了，没用
> 
> 还是有点没看懂你的意思。是说你已经设置好了备用音源，但是它匹配出来的歌曲都不是原版，没有歌词和评论吗？你可以把有问题的歌曲发一下，我这边也测试看看是否正常。

我说的是，原来他那个yesplaymusic，停止更新了，现在很多音源都有问题，你的这个，我现在报错打不开，自己也试着构建了，也是不能用

**Comment by stark81** [comment]
> 我说的是，原来他那个yesplaymusic，停止更新了，现在很多音源都有问题，你的这个，我现在报错打不开，自己也试着构建了，也是不能用

在终端里用yarn electron:serve直接启动服务看看能不能用？

**Comment by YvGuo-YY** [comment]
不行，登陆不上去只能听原本ypm缓存的音乐（非自己下载）

**Comment by YvGuo-YY** [comment]
<img width="1001" alt="image" src="https://github.com/stark81/my_yesplaymusic/assets/54350593/04ffdd34-620d-4aff-9ba2-977ae4778536">

**Comment by stark81** [comment]
> 不行，登陆不上去只能听原本ypm缓存的音乐（非自己下载）

看你这个描述，是可以打开软件的，只是每个页面都无法加载内容，但可以直接点击下面的播放按钮放歌吗？
我之前遇到过这种情况，好像是dns污染来着，更换一下dns解析服务器试试？

**Comment by YvGuo-YY** [comment]
> > 不行，登陆不上去只能听原本ypm缓存的音乐（非自己下载）
> 
> 看你这个描述，是可以打开软件的，只是每个页面都无法加载内容，但可以直接点击下面的播放按钮放歌吗？ 我之前遇到过这种情况，好像是dns污染来着，更换一下dns解析服务器试试？

不行呢，而且能加载，只是播放不了歌

**Comment by stark81** [comment]
> > > 不行，登陆不上去只能听原本ypm缓存的音乐（非自己下载）
> > 
> > 
> > 看你这个描述，是可以打开软件的，只是每个页面都无法加载内容，但可以直接点击下面的播放按钮放歌吗？ 我之前遇到过这种情况，好像是dns污染来着，更换一下dns解析服务器试试？
> 
> 不行呢，而且能加载，只是播放不了歌

打开“开发者工具”看看有没有什么报错吧，在电脑左上角的“窗口”-“开发者工具”那里

**Comment by stark81** [comment]
没有回复我就关闭了，以后遇到相同的问题也请开新的issue吧
