### ISSUE TITLE
优先本地容易崩溃

### ISSUE THREAD

**Issue by Ririsu-Kokoromu** [stark81/my_yesplaymusic#10]
Windows客户端
好像开启优先本地之后手动切换下一首到有本地资源的歌会导致软件崩溃，我把优先本地关了就没崩溃过了
![image](https://github.com/stark81/my_yesplaymusic/assets/120046369/9c70816f-60de-4c76-a36a-9c73edfaf549)

**Comment by stark81** [comment]
是软件直接退出了吗？还是别的什么现象呢

**Comment by Ririsu-Kokoromu** [comment]
卡着一直没反应 点也点不了> 是软件直接退出了吗？还是别的什么现象呢

**Comment by stark81** [comment]
这个问题在我这边一直都没有成功复现，可以尝试安装新版本再试一试哦

**Comment by Ririsu-Kokoromu** [comment]
> 这个问题在我这边一直都没有成功复现，可以尝试安装新版本再试一试哦

换了最新版本好像没这个问题了，我刚刚试了一下也没出现问题

**Comment by stark81** [comment]
你的来信已经收到，我将会尽快给你回复。
