### ISSUE TITLE
MacOS Sonoma 14.1 开启客户端之后状态栏出现空白无用图标

### ISSUE THREAD

**Issue by MamboJiang** [stark81/my_yesplaymusic#11]
开启客户端之后，在状态栏会出现两个看不见的图标（如图）
按上去可以看到有占位, 但是没有任何反应
<img width="508" alt="Screenshot 2023-12-26 at 13 39 43" src="https://github.com/stark81/my_yesplaymusic/assets/60293500/fc278518-b9cc-467b-a123-5b9a3bf1c301">
系统是macOS Sonoma14.1, 电脑是MacBookPro2022, M2
从Release下载的打不开，所以是用Node16.16自己打包的，没有做任何修改

**Comment by stark81** [comment]
1. 是否在设置里开启了状态栏歌词的按钮呢？
2. 既然是自己打包的，那可以先用yarn electron:serve启动，看看有没有什么报错信息？

**Comment by MamboJiang** [comment]
确实报了macStatusBarLyric的错
<img width="508" alt="Screenshot 2023-12-27 at 09 26 09" src="https://github.com/stark81/my_yesplaymusic/assets/60293500/fee6ca0e-617c-4947-a450-1b9d0a14ce9d">

终端里这个module not found，装的时候说abstract-socket不支持darwin平台
<img width="981" alt="Screenshot 2023-12-27 at 09 21 45" src="https://github.com/stark81/my_yesplaymusic/assets/60293500/bca1d65e-6085-4852-a024-69d549860f7c">

如果是包的问题，yarn install的时候确实报了警告
<img width="982" alt="Screenshot 2023-12-27 at 09 28 27" src="https://github.com/stark81/my_yesplaymusic/assets/60293500/67f6c918-0668-48e1-91be-7045b4a40c63">

**Comment by stark81** [comment]
> module not found，装的时候说abstract-socket不支持darwin平台

应该和这个没有关系。看报错和remote.getGlobal有关，应该是和electron有关，你可以先试着把yarn.lock文件删掉，然后uninstall掉electron，然后把package里的electron的版本改成"electron": "^13.6.7", 我这边实际安装的版本是13.6.9，你可以手动安装一下这个版本的electron再试一下

**Comment by MamboJiang** [comment]
换了版本，编译不了了。 就算把项目删了 清完缓存从头开始安装也不行。
应该还有其他的包是版本不一样的吧？
<img width="738" alt="Screenshot 2023-12-27 at 13 13 30" src="https://github.com/stark81/my_yesplaymusic/assets/60293500/dd3b08bb-2fdf-45fa-9324-4bffb49ab5bc">

<img width="1138" alt="Screenshot 2023-12-27 at 13 12 03" src="https://github.com/stark81/my_yesplaymusic/assets/60293500/9f752f6d-07da-4f49-8d57-63e959172b45">

**Comment by stark81** [comment]
是，"NeteaseCloudMusicApi": "4.8.10",package把NeteaseCloudMusicApi改成这样吧，最新版本的网易云API更新了一些依赖文件，会导致报错，改成这个。

或者，你可以直接替换成0.4.7的那个yarn.lock，然后再安装依赖试试。

**Comment by MamboJiang** [comment]
还是会报错...
会不会是electron builder之类的版本的问题
[errorlog.txt](https://github.com/stark81/my_yesplaymusic/files/13776693/errorlog.txt)

**Comment by stark81** [comment]
不知道哦。

你可以先把代码删了，拉一下我这里0.4.7那个版本的代码，自己构建一下看看能不能跑？我感觉还是后面代码的依赖文件有问题，你可以试试第一版的。如果可以跑的话，你再拉更新到最新代码试试。

**Comment by MamboJiang** [comment]
还真成了，用0.4.7的yarn install了之后直接拉最新的构建就可以了
