### ISSUE TITLE
右下角进入歌词界面时不会自动刷新歌词位置？

### ISSUE THREAD

**Issue by MamboJiang** [stark81/my_yesplaymusic#12]
官方版本的YesPlayMusic在打开歌词界面时会自动刷新一次歌词位置，
而这个版本的YesPlayMusic只有在切换到下一句的时候才会刷新位置，进入歌词界面的时候还是上次关闭时的位置，如果一首曲子没有打开过歌词界面的话就是歌曲开头
是否考虑改成官方版的模式？

**Comment by stark81** [comment]
我看看，这个地方可能是增加的评论功能导致的，我测试一下。

M芯片版本应该也有状态栏歌词之类的吧？

**Comment by MamboJiang** [comment]
有的，状态栏和Touch Bar歌词都是正常的
