### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by hold88888888** [stark81/my_yesplaymusic#13]
![屏幕截图 2024-01-25 153652](https://github.com/stark81/my_yesplaymusic/assets/105548184/dedfde6a-735a-4f63-a556-862df0f57e6f)
![屏幕截图 2024-01-25 153740](https://github.com/stark81/my_yesplaymusic/assets/105548184/9abebb59-a7cd-4d75-8445-24db7dfb131a)

**Comment by hold88888888** [comment]
![屏幕截图 2024-01-25 153936](https://github.com/stark81/my_yesplaymusic/assets/105548184/0641cd10-aa81-4d68-a72d-74f1bde69b3a)

**Comment by stark81** [comment]
应该是你播放了一些本地歌曲，这个歌曲还没有进行匹配，然后你关闭了程序，再打开就出现了这个问题。。
这个是当前已经打包好的程序的bug，虽然已经修复了，但是修复好的代码还没有进行打包。。
暂时的解决方法有两种：
1. 可以打开软件的开发者工具(Windows版本的打开方式可以参考chrome浏览器打开开发者工具的快捷键)，然后在控制台输入resetPlayer();回车后刷新页面即可。只要你本地歌曲都匹配后就不会出现这个问题了；或者是你关闭程序之前播放的歌曲是线上的或者是匹配后的也不会再出现这个问题；
2. 第二种方法则是自己拉去最新的代码，自己打包一下，也不会再出现这个问题。

**Comment by hold88888888** [comment]
万分感谢！！我马上去试一下~

**Comment by hold88888888** [comment]
okk(￣▽￣)～■干杯
