### ISSUE TITLE
无法播放音乐

### ISSUE THREAD

**Issue by hydd30** [stark81/my_yesplaymusic#15]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

系统为arch linux，之前用的原版yesplaymusic 0.4.7，从aur下载的my-yesplaymusic-bin-0.4.13-2，软件刚下载下来还能正常使用，过了一会不知为何就切不了歌了。并且播放键均失效（无论是双击播放还是右键播放）
打开控制台，按另一个issue的办法使用resetPlayer之后，双击播放歌曲，下方播放栏也不显示歌曲，控制台提示GET 404 Error
![2024-01-30_01-28](https://github.com/stark81/my_yesplaymusic/assets/52079469/a35687ad-737b-4cae-9d0a-765cb570cc49)

此时左右键切换歌曲或者双击播放其他歌曲，控制台则会提示TypeError，具体如下图
![2024-01-30_01-30](https://github.com/stark81/my_yesplaymusic/assets/52079469/a9e698fb-a733-49db-96a2-16c4c43f447f)

换回原先的yesplaymusic 0.4.7则又一切正常。（但my-yesplaymusic的桌面歌词和评论区真的很喜欢）

此外，在另一个issue中提到的状态栏存在两个图标的问题仍然存在，黑色图标有用，白色没用
![2024-01-30_01-38](https://github.com/stark81/my_yesplaymusic/assets/52079469/765e8c76-bb6c-4d99-872b-310a47a89dc1)

**Comment by stark81** [comment]
1. 播放的是线上歌曲还是本地歌曲？
2. resetPlayer();之后是否有ctrl + r刷新页面呢？

**Comment by hydd30** [comment]
> 1. 播放的是线上歌曲还是本地歌曲？
> 2. resetPlayer();之后是否有ctrl + r刷新页面呢？

线上歌曲；刷新了

**Comment by stark81** [comment]
刷新之后是又可以用了，然后过一段时间又不可用，还是刷新之后一直都不可用？

**Comment by hydd30** [comment]
> 刷新之后是又可以用了，然后过一段时间又不可用，还是刷新之后一直都不可用？

一直不可用。
另外今天打开又出了个问题，在线歌单打开一片空白了，控制台一直弹TypeError的错
![2024-01-30_20-10](https://github.com/stark81/my_yesplaymusic/assets/52079469/85d5f615-eb6f-48c2-a0ec-8e7f56dfa8dd)
![2024-01-30_20-11](https://github.com/stark81/my_yesplaymusic/assets/52079469/2accab7b-e02c-4d95-82ec-84545b306808)

ps：我就尝试性改过设置里的代理。其他设置直接从yesplaymusic自动继承的

**Comment by stark81** [comment]
可以用另一个resetApp();完全重置软件试试，这样做的话本地音乐信息什么的都会没了的(但不会删除本地音乐的文件)，如果有本地音乐的话可以先在设置里进行备份哦。重置后重新登录应该就可以用了，然后看看你那边能不能复现吧。

**Comment by hydd30** [comment]
> 可以用另一个resetApp();完全重置软件试试，这样做的话本地音乐信息什么的都会没了的(但不会删除本地音乐的文件)，如果有本地音乐的话可以先在设置里进行备份哦。重置后重新登录应该就可以用了，然后看看你那边能不能复现吧。

还真是，行了

**Comment by stark81** [comment]
> > 可以用另一个resetApp();完全重置软件试试，这样做的话本地音乐信息什么的都会没了的(但不会删除本地音乐的文件)，如果有本地音乐的话可以先在设置里进行备份哦。重置后重新登录应该就可以用了，然后看看你那边能不能复现吧。
> 
> 还真是，行了，万分感谢。不过话说这是什么原因

不清楚哦，你这里的报错具体到了某行代码了，看着像是在替换播放列表时报错了，你可以按照之前的操作再试一次。。
