### ISSUE TITLE
Windows和Linux会出现空白图标的问题；

### ISSUE THREAD

**Issue by stark81** [stark81/my_yesplaymusic#16]

**Comment by scgm0** [comment]
还是有这个问题，会多出一个electron13的空白系统托盘，原版没有这个问题

**Comment by stark81** [comment]
> 还是有这个问题，会多出一个electron13的空白系统托盘，原版没有这个问题

新版再测试哈，应该没啥问题了。。

**Comment by scgm0** [comment]
> > 还是有这个问题，会多出一个electron13的空白系统托盘，原版没有这个问题
> 
> 新版再测试哈，应该没啥问题了。。

好耶！我是用aur安装的，等待更新中
