### ISSUE TITLE
系统托盘的“加入喜欢”选项不会变化

### ISSUE THREAD

**Issue by scgm0** [stark81/my_yesplaymusic#17]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

如图，歌曲已经加入喜欢了，它应该显示取消喜欢，虽然文本显示不正确，但功能正常。
![图片](https://github.com/stark81/my_yesplaymusic/assets/52148221/71996c88-1a8b-4013-a815-37ee7257d5a5)

**Comment by stark81** [comment]
最新版解决了哦
