### ISSUE TITLE
绑定last.fm点击第三方应用授权确认后无反应

### ISSUE THREAD

**Issue by EmpCCC** [stark81/my_yesplaymusic#2]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://github.com/stark81/my_yesplaymusic/assets/68339311/f69854e1-44c5-4b83-a193-4113040ac71c)
刚刚从原版切换到这个版本，原版可以成功绑定

**Comment by stark81** [comment]
我这边是没有问题的哦。特地去注册了一个账号测试了一下。
![lastfm0](https://github.com/stark81/my_yesplaymusic/assets/48707376/ed3796e1-382d-40bc-885e-e98f1edaf061)
![lastfm1](https://github.com/stark81/my_yesplaymusic/assets/48707376/e1107681-1782-4108-8f53-6a470c6c4fcc)

**Comment by stark81** [comment]
Mac版没有问题，我先试试windows版本有没有问题吧。。

**Comment by stark81** [comment]
我这边windows版本也是授权之后无法跳转回来，暂时没有什么思路解决。你可以试一下用原版连接好之后再用我这个版本去覆盖，这样可能可以
