### ISSUE TITLE
[feature]可以在Release中加入rpm支持吗

### ISSUE THREAD

**Issue by zxc2012** [stark81/my_yesplaymusic#24]
如题，原项目可以下载rpm package

**Comment by stark81** [comment]
好像是下载rpm打包依赖时出错了，不知道和我Linux版本有关，有时间我换个Linux再试试吧。。

**Comment by zxc2012** [comment]
ok, 如果有需要可以帮忙。我在fedora上使用nodejs16可以正常打包，但文件超过20MB了就没传上来，你是使用的github action上传release吗？

**Comment by stark81** [comment]
> ok, 如果有需要可以帮忙。我在fedora上使用nodejs16可以正常打包，但文件超过20MB了就没传上来，你是使用的github action上传release吗？

创建release的时候直接上传的。
