### ISSUE TITLE
m2芯片，打开之后本地音乐空白，在线音乐无法播放

### ISSUE THREAD

**Issue by fireontable** [stark81/my_yesplaymusic#25]
![截屏2024-03-25 18 30 02](https://github.com/stark81/my_yesplaymusic/assets/12096169/a71683f2-855e-4b94-9ac7-cfdaca248a49)

用的客户端，mac os sonoma 14.4 (23E214

**Comment by stark81** [comment]
是覆盖旧版本的吗？还是第一次安装的呢？

打开“开发者工具”，输入"resetPlayer()"后刷新一下页面试试

**Comment by fireontable** [comment]
覆盖旧版本，开发者工具在哪里打开啊

**Comment by fireontable** [comment]
![截屏2024-03-25 19 43 34](https://github.com/stark81/my_yesplaymusic/assets/12096169/3ed7e2e9-2c32-4978-adab-b1131d435959)
刷新了一下，可以播放了，可是本地音乐显示不出来

**Comment by stark81** [comment]
1. 之前有使用过“导出本地歌曲信息”导出过本地音乐信息吗？如果有的话，就可以：在设置里清空本地音乐信息，然后在开发者工具里输入resetPlayer()，然后刷新页面，然后重新导入本地歌曲信息 应该就可以了；
2. 如果之前没有导出过的话，那么请在开发者工具里输入：JSON.parse(localStorage.getItem('localMusic'))，会显示你的本地音乐信息，然后你可以点击那个“copy object”把它保存到本地。保存之后你自己打开看看里面是不是有你的音乐信息，但没有“version”的字段(如下图所示)
![image](https://github.com/stark81/my_yesplaymusic/assets/48707376/f0fd3053-6ec5-41f9-8858-7dfb19ce14cc)
![image](https://github.com/stark81/my_yesplaymusic/assets/48707376/2f5c3933-aa86-4430-930e-2c200e5c1db5)
然后按照第一步来进行了

**Comment by stark81** [comment]
问题解决了吗？。。

**Comment by stark81** [comment]
> 只有X64版本,m系列芯片跑的话是运行在转译器上,效率低.希望以后能出原生arm版吧

我只有x64的机子，打包出来的arm版本没法跑。可以拉代码自己打包哈
