### ISSUE TITLE
无法正常启动程序

### ISSUE THREAD

**Issue by zhusun890** [stark81/my_yesplaymusic#3]
设备: MacBook Pro 2021, M1 Max
操作系统: macOS Sonoma 14.0 Beta 7

相似情况: #1 

复现步骤：
 1. 从 Releases 下载 arm64 / universal 版本安装包
 2. 拖拽进 Applications
 3. 使用 xattr -r -d com.apple.quarantine /Applications/YesPlayMusic.app 移除隔离属性
 4. 从启动台或访达启动程序
 5. 程序报错，弹窗
<img width="632" alt="image" src="https://github.com/stark81/my_yesplaymusic/assets/65890314/2bc6a3a4-088a-4860-8712-dcb7b6dbad78">

点击确定后，程序未退出，但没有窗口显示，macOS 顶部状态栏的控件可以正常点击，点击 Toggle Developer Tools 无响应
<img width="968" alt="image" src="https://github.com/stark81/my_yesplaymusic/assets/65890314/1bfe3236-df73-47d9-a6a1-c64a42e5ec1e">

**Comment by stark81** [comment]
我这边没有M芯片的电脑咧。你先试试官方的0.4.7版本是否正常？第3步是M芯片安装软件后的必要步骤吗？

**Comment by zhusun890** [comment]
第三步是的，官方版本可以正常运行

**Comment by stark81** [comment]
> 第三步是的，官方版本可以正常运行

可能是因为我电脑不是M芯片的，所以打包时不会下载arm相关的依赖？建议你自己打包一下吧。。

**Comment by MamboJiang** [comment]
同样的报错，M2，macOS14.1

**Comment by t13528829926** [comment]
我也碰到这个报错了

**Comment by t13528829926** [comment]
> 同样的报错，M2，macOS14.1 亲测用Node16自己打包就可以正常使用了

打包的安装包可以分享下吗？谢谢！

**Comment by stark81** [comment]
> 我也碰到这个报错了

因为我自己电脑是intel芯片的，打包出来的程序M芯片用不了。。可以尝试自己打包，或者发邮件给[MamboJiang](https://github.com/MamboJiang)，让他发一下他打包好的程序哦
