### ISSUE TITLE
Compile Steps Please? 

### ISSUE THREAD

**Issue by Ff-c109** [stark81/my_yesplaymusic#32]
# 尽量每个 issue 只提一个 bug 或新功能
May I install it by source? I hope steps could be found in README, but there isn't any...
### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by stark81** [comment]
没太懂，是因为没有你平台的安装包，想要自己打包吗？如果是的话：
1. git clone 本仓库代码到本地；
2. 安装node和yarn，其中node版本为14或者16；
3. 使用yarn install安装依赖；
4. 复制 /.env.example 文件为 /.env
5. yarn electron:build 打包客户端

![image](https://github.com/stark81/my_yesplaymusic/assets/48707376/9af09013-00d8-4b74-b402-9e561240f602)

**Comment by Ff-c109** [comment]
哦哦，明白了，谢谢
