### ISSUE TITLE
添加本地文件夹，不能搜索文件下的内容

### ISSUE THREAD

**Issue by slm93gic** [stark81/my_yesplaymusic#33]
RT

**Comment by stark81** [comment]
开发者模式下，看看有没有报错信息？

**Comment by slm93gic** [comment]
> 开发者模式下，看看有没有报错信息？

function T(e) {
            return e.includes("&") ? e = e.split("&") : e.includes("、") ? e = e.split("、") : e.includes(",") ? e = e.split(",") : e.includes("/") && (e = e.split("/")),
            e
        }

TypeError: Cannot read property 'includes' of undefined
![微信截图_20240606104038](https://github.com/stark81/my_yesplaymusic/assets/37533212/5268b363-3bc9-433e-a98d-4e082449bc90)

**Comment by stark81** [comment]
当前这个软件读取本地歌曲的歌手信息时，是读取歌曲元数据，而不是读取歌曲文件路径里的。你现在这个报错是歌曲元数据里缺少了歌手信息，所以导致的报错。

对于歌手信息的获取问题，因为每个用户的本地歌曲存放格式是不一样的，有的是用歌手作为文件夹存放他的所有歌曲，有的则是直接在歌曲名称里加上了歌手名字，有的甚至就没有在路径里保存歌手信息等。所以，我这里只写了读取元数据里，因为大部分歌曲的元数据里都会保存这些信息。

至于你现在这个报错，暂时有两种办法：
1. 修改程序，获取不到歌手时，直接返回空白。但这个会导致无法匹配线上歌曲，也获取不了歌词等所有信息，而且很有可能会导致精确匹配功能也出错，所以不太建议；
2. 你手动修改歌曲元数据。Mac用户可以直接使用Apple Music修改，而windows的话也可以下载Apple Music来修改

**Comment by slm93gic** [comment]
因为读取不到源数据，导致异常导入，个人感觉用歌词换导入这种权重不太合适吧，而已有些人不一定回懂得mp3tag信息的修改。

**Comment by stark81** [comment]
这个不是歌词啊，是歌手啊。而且这个报错肯定是当初写功能的时候考虑不周导致的bug咯，自然不会是设计成“读取不到元数据就阻止导入”，只是说这个bug可以从源头上把问题暴露出来，否则就会导入成功了，但是后面死活匹配不上线上信息，而且还没有显示原因。总之呢，这些都是设计不到位导致的bug。

因为我本身还在做一些其他功能，暂时还没法发包，所以如果说你不太想修改元数据的话，那么我建议你自己修改打包一下？
可以修改：src/store/actions.js里的splitArtist函数，在函数第一行加上if (!artist) return '未知歌手';

![image](https://github.com/stark81/my_yesplaymusic/assets/48707376/7b2151ed-a5b4-4001-9eea-61a6546622f3)

**Comment by slm93gic** [comment]
ok。使用了MP3tag 定位出一些歌曲存在的问题，我自己打包试一下，感谢百忙之中回复我的疑问。
