### ISSUE TITLE
疑似风控，封号警告

### ISSUE THREAD

**Issue by moetayuko** [stark81/my_yesplaymusic#35]
我用的是 my_yesplaymusic，从 24/9/17 开始每隔 2~3 天就自动退出登录并强制重置密码，今天喜提封号

搜索发现 YesPlayMusic 那边有大量用户反馈同样的问题 https://github.com/qier222/YesPlayMusic/issues/2299

建议在查明原因之前停止使用 YesPlayMusic 及衍生品

**Comment by stark81** [comment]
使用了NeteaseCloudMusicApi项目来作为API的都有这个问题，应该是网易那边的安全策略改了吧，只能等API项目那边更新了。

**Comment by moetayuko** [comment]
刚去 api 项目开了个 issue

**Comment by stark81** [comment]
更新API项目后，问题解决

**Comment by moetayuko** [comment]
@stark81 api 项目新版又改了一些 cookie 相关的东西，希望再跟进一下

**Comment by stark81** [comment]
> @stark81 api 项目新版又改了一些 cookie 相关的东西，希望再跟进一下

等我小号解封之后看看。。

**Comment by 111inhistory** [comment]
> > @stark81 api 项目新版又改了一些 cookie 相关的东西，希望再跟进一下
> 
> 等我小号解封之后看看。。

我个人测试是因为上游NCMAPI使用的是iOS的Header登录网易云导致的，前几个月我向上游提交了当时最新的Header，但是不是很有用，虽然至少没被封。改用上游已有的PC端Header是不会退登的，目前使用了差不多2个月没有问题（理论上来说，这个接口可以通过前端向后端发送的cookie控制登录请求的，但是我不会改代码，所以把后端默认的Header改了然后重打包😭）

**Comment by stark81** [comment]
> 我个人测试是因为上游NCMAPI使用的是iOS的Header登录网易云导致的，前几个月我向上游提交了当时最新的Header，但是不是很有用，虽然至少没被封。改用上游已有的PC端Header是不会退登的，目前使用了差不多2个月没有问题（理论上来说，这个接口可以通过前端向后端发送的cookie控制登录请求的，但是我不会改代码，所以把后端默认的Header改了然后重打包😭）

感觉挺奇怪的，这个项目和我自己的另一个项目都使用了最新的API，但那个项目就没啥问题，能稳定登陆使用，和以前相比就少了一个听歌记录的功能，但这边这个就一直出现掉登陆的问题。。。找个时间看看header的东西再看看怎么改
