### ISSUE TITLE
打开软件之后状态栏生成一个没用的图标

### ISSUE THREAD

**Issue by YLRK** [stark81/my_yesplaymusic#4]
客户端，Windows11和Ubuntu22.04
打开yesplaymusic，Windows端和linux端都会存在一个没有用的状态栏图标
windows下
![image](https://github.com/stark81/my_yesplaymusic/assets/55654587/c2462b3a-0588-4815-987a-df19a894d22f)
linux下
![image](https://github.com/stark81/my_yesplaymusic/assets/55654587/0ea3f536-82ab-4ca5-84e6-3bb2a0b0e1ca)

**Comment by stark81** [comment]
有用的呀
![linux](https://github.com/stark81/my_yesplaymusic/assets/48707376/605728db-536f-46f1-9cf5-d61a357004fd)

**Comment by YLRK** [comment]
我是说旁边这个
![image](https://github.com/stark81/my_yesplaymusic/assets/55654587/cdcd3a9f-652a-4294-ab9b-3675cb777158)

**Comment by stark81** [comment]
OK，我记录一下

**Comment by stark81** [comment]
v0.4.14版本已修复
