### ISSUE TITLE
文件损坏，直接打不开了，mac13版本

### ISSUE THREAD

**Issue by lnsslimbo** [stark81/my_yesplaymusic#5]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by stark81** [comment]
你的来信已经收到，我将会尽快给你回复。

**Comment by stark81** [comment]
截个图看看呗，电脑是intel的还是M芯片的呢

**Comment by EdsonWong** [comment]
> 截个图看看呗，电脑是intel的还是M芯片的呢

建议更改一下 readme 部分，M 芯片需要自行打包才能打开。更新一下 git clone那里为这个项目的链接即可，另外 nodejs 版本需要 16. 实测打包通过，成功运行（M1pro）

**Comment by stark81** [comment]
你的来信已经收到，我将会尽快给你回复。

**Comment by stark81** [comment]
> > 截个图看看呗，电脑是intel的还是M芯片的呢
> 
> 建议更改一下 readme 部分，M 芯片需要自行打包才能打开。更新一下 git clone那里为这个项目的链接即可，另外 nodejs 版本需要 16. 实测打包通过，成功运行（M1pro）

好的，谢谢提的建议。

**Comment by Ancvor** [comment]
> M芯片的话：
> 
> 1. 把当前代码删除，然后重新拉取代码；
> 2. 切换到0.4.7的那个tag，然后安装依赖；
> 3. 安装完成之后，切换到最新的分支，按照readme进行构建即可。

m1用不了，小白不会弄啊求大佬更新🥹

**Comment by stark81** [comment]
> > M芯片的话：
> > 
> > 1. 把当前代码删除，然后重新拉取代码；
> > 2. 切换到0.4.7的那个tag，然后安装依赖；
> > 3. 安装完成之后，切换到最新的分支，按照readme进行构建即可。
> 
> m1用不了，小白不会弄啊求大佬更新🥹

M芯片只能你们自己构建哦，我intel芯片构建出来arm版的用不了。大致步骤如下：
1. 安装node16，然后安装yarn；
2. git clone 当前仓库；
3. 切换至tag 0.4.7：git checkout 0.4.7；
4. 使用yarn 安装依赖：yarn install；
5. 安装成功后，切换回最新的代码：git checkout main;
6. 构建：yarn electron:build;

**Comment by Ancvor** [comment]
感谢大佬回复，但是我没接触过这个确实不会弄，喜欢yesplay但是没有状态栏歌词特别难受，才找到您的项目。我自己肯定是没法弄😂这东西方便远程操作么？我可以把我的电脑远程给您构建，然后还能更新git上的安装包？

**Comment by stark81** [comment]
> 感谢大佬回复，但是我没接触过这个确实不会弄，喜欢yesplay但是没有状态栏歌词特别难受，才找到您的项目。我自己肯定是没法弄😂这东西方便远程操作么？我可以把我的电脑远程给您构建，然后还能更新git上的安装包？

可以啊，我可以远程操作一次，之后如果有更新的话，你就可以自己操作了。

**Comment by Ancvor** [comment]
太感谢了哥，我看你操作以后自己也能弄了。你什么时候有时间，我随时都可以。

**Comment by stark81** [comment]
> 太感谢了哥，我看你操作以后自己也能弄了。你什么时候有时间，我随时都可以。

现在就可以，你把qq发一下，我加完之后你再删掉就可以了

**Comment by Ancvor** [comment]
qq：471419299Sent from my iPhoneOn Jan 29, 2024, at 16:49, stark81 ***@***.***> wrote:﻿

太感谢了哥，我看你操作以后自己也能弄了。你什么时候有时间，我随时都可以。

现在就可以，你把qq发一下，我加完之后你再删掉就可以了

**Comment by doubledeft** [comment]
补充一下上面的操作还需要 复制 /.env.example 文件为 /.env 。
但我不确定要不要本地部署NeteaseCloudMusicApi，控制台网络查看访问的接口，http://localhost:27232下的api返回的都为空。

**Comment by stark81** [comment]
> 补充一下上面的操作还需要 复制 /.env.example 文件为 /.env 。 但我不确定要不要本地部署NeteaseCloudMusicApi，控制台网络查看访问的接口，[http://localhost:27232下的api返回的都为空。](http://localhost:27232%E4%B8%8B%E7%9A%84api%E8%BF%94%E5%9B%9E%E7%9A%84%E9%83%BD%E4%B8%BA%E7%A9%BA%E3%80%82)

只要你serve或者build出来的软件首页能正常看到图片就是正常的，不需要单独运行NeteaseCloudMusicApi，除非你是要运行网页版

**Comment by doubledeft** [comment]
尝试了一下，server和build出来的软件都可以看到图片。但是build出来的软件，无法播放歌曲，控制台报错为
<img width="1125" alt="image" src="https://github.com/stark81/my_yesplaymusic/assets/58928569/2b8169f5-a39c-44ba-b26e-6818fdbffb69">
相对应server出来的软件控制台则没有图中的报错。

**Comment by stark81** [comment]
先用resetPlayer()清除一下播放器状态，然后刷新一下

**Comment by stark81** [comment]
> 尝试了一下，server和build出来的软件都可以看到图片。但是build出来的软件，无法播放歌曲，控制台报错为 <img alt="image" width="1125" src="https://private-user-images.githubusercontent.com/58928569/301827716-2b8169f5-a39c-44ba-b26e-6818fdbffb69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzM4NjgsIm5iZiI6MTcwNjg3MzU2OCwicGF0aCI6Ii81ODkyODU2OS8zMDE4Mjc3MTYtMmI4MTY5ZjUtYTM5Yy00NGJhLWIyNmUtNjgxOGZkYmZmYjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDExMzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZTMxMGFlNjZhODA3M2U1NmY1MWY2MDZhODZhMzI0MmQxMWFmMTI1ZTZhMDg3NjNlOWNhZGZiZjkxN2IzYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.utzB8xRuyDUfULNbIsuRdTiwRS18HOoppc1ISgBhuJM"> 相对应server出来的软件控制台则没有图中的报错。

先用resetPlayer()清除一下播放器状态，然后刷新一下

**Comment by doubledeft** [comment]
> > 尝试了一下，server和build出来的软件都可以看到图片。但是build出来的软件，无法播放歌曲，控制台报错为 <img alt="image" width="1125" src="https://private-user-images.githubusercontent.com/58928569/301827716-2b8169f5-a39c-44ba-b26e-6818fdbffb69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzM4NjgsIm5iZiI6MTcwNjg3MzU2OCwicGF0aCI6Ii81ODkyODU2OS8zMDE4Mjc3MTYtMmI4MTY5ZjUtYTM5Yy00NGJhLWIyNmUtNjgxOGZkYmZmYjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDExMzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZTMxMGFlNjZhODA3M2U1NmY1MWY2MDZhODZhMzI0MmQxMWFmMTI1ZTZhMDg3NjNlOWNhZGZiZjkxN2IzYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.utzB8xRuyDUfULNbIsuRdTiwRS18HOoppc1ISgBhuJM"> 相对应server出来的软件控制台则没有图中的报错。
> 
> 先用resetPlayer()清除一下播放器状态，然后刷新一下

确实是这样的，刚发现readme里特性有提到reset一下。刷新了就没有问题了。
