### ISSUE TITLE
好像不像是完全本地播放

### ISSUE THREAD

**Issue by Violexjj** [stark81/my_yesplaymusic#9]
如题所示，当我关掉网之后，歌词、封面什么的都不能显示了。大佬应该是通过网易云匹配获取的，所以有些封面也和我歌曲的内嵌封面不一致。
不过问题不大，因为我只是来试一下滴，重点是想要向大佬请教，或者说帮忙，我也做了一个本地音乐播放器，是纯本地的，不联网。它是读取内嵌歌词或者是本地lrc文件，但是我想升级一下，如果本地获取不到就像你一样从网易云获取，但是我不咋会弄。能不能加个QQ聊聊：3059557534
我的播放器在b站的介绍地址：https://www.bilibili.com/video/BV1or4y1X7hc/

**Comment by Violexjj** [comment]
而且我第一次打开，扫描完之后，本地音乐还是空的。重启才有。
然后我断网之后，不管怎么重启，都显示不了歌曲了，就很怪。

**Comment by stark81** [comment]
> 而且我第一次打开，扫描完之后，本地音乐还是空的。重启才有。 然后我断网之后，不管怎么重启，都显示不了歌曲了，就很怪。

截个图看看？
